MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: "./pretrained/"
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'part_attention_vit'
  NO_MARGIN: True
  METRIC_LOSS_TYPE: 'class_aware_triplet'
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_large_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]

INPUT:
  SIZE_TRAIN: [384,384]
  SIZE_TEST: [384,384]
  DO_FLIP: False
  REA:
    ENABLED: False
    PROB: 0.5
    SH: 0.15
    SL: 0.02
    R1: 0.3
  CJ:
    ENABLED: False
    PROB: 0.5
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    SATURATION: 0.10
    HUE: 0.05
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  LGT: # Local Grayscale Transfomation
    DO_LGT: True
    PROB: 0.5

DATASETS:
  TRAIN: ('UrbanElementsReID',)
  TEST: ('UrbanElementsReID',)
  ROOT_DIR: '/kaggle/input/datasets/gloriagcuenco/urban2026/Urban2026'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 40
  BASE_LR: 0.001 # 0.0004 for msmt
  IMS_PER_BATCH: 32
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 60
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  SEED: 1234

TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: True

LOG_ROOT: 'models/' # root of log file
TB_LOG_ROOT: './tb_log/'
LOG_NAME: './model'
